server:
  port: 8082
spring:
  mvc:
    pathmatch:
      api-prefix: /api
  application:
    name: manufacturing-order

  datasource:
    url: jdbc:postgresql://localhost:5466/manufacturing_order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: localhost:9092
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: 1
  show-actuator: false